2018-03-11 00:22:48,440 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:09:10,439 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:09:42,280 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:09:47,832 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:18:00,104 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:18:06,223 ERROR: Exception on / [GET] [in /Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_login/utils.py", line 227, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_login/login_manager.py", line 165, in unauthorized
    return redirect(login_url(login_view, request.url))
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_login/utils.py", line 97, in login_url
    base = url_for(login_view)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'auth.login'. Did you mean 'main.index' instead?
2018-03-11 20:19:26,379 ERROR: Exception on / [GET] [in /Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_login/utils.py", line 227, in decorated_view
    return current_app.login_manager.unauthorized()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_login/login_manager.py", line 165, in unauthorized
    return redirect(login_url(login_view, request.url))
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask_login/utils.py", line 97, in login_url
    base = url_for(login_view)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/helpers.py", line 323, in url_for
    force_external=external)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/werkzeug/routing.py", line 1768, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'auth.login'. Did you mean 'main.index' instead?
2018-03-11 20:19:41,594 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:20:37,942 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:22:36,570 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:22:39,232 ERROR: Exception on / [GET] [in /Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/main/routes.py", line 27, in index
    form = PostForm()
NameError: global name 'PostForm' is not defined
2018-03-11 20:23:32,830 INFO: Obm startup [in /Users/wangzi/Desktop/my_guraduation_design/obm/app/__init__.py:77]
2018-03-11 20:23:35,598 ERROR: Exception on / [GET] [in /Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wangzi/Desktop/my_guraduation_design/obm/app/main/routes.py", line 48, in index
    return render_template('index.html', title=_('Home'))
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 57, in get_source
    return self._get_source_fast(environment, template)
  File "/Users/wangzi/anaconda/envs/flask/lib/python2.7/site-packages/flask/templating.py", line 85, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: index.html
